[tools]
bat = "latest"
eza = "latest"
fzf = "latest"
gh = "latest"
hcloud = "latest"
helm = "latest"
k9s = "latest"
kubectl = "latest"
kustomize = "latest"
lazygit = "latest"
neovim = "0.10.4"
node = "lts"
python = "latest"
ripgrep = "latest"
ruby = "3.3.7"
terraform = "latest"
terraform-docs = "latest"
